/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#pragma once

#include <glib-object.h>


G_BEGIN_DECLS

/* enumerations from "cui-call.h" */


GType cui_call_state_get_type (void);
#define CUI_TYPE_CALL_STATE (cui_call_state_get_type())

G_END_DECLS

/* Generated data ends here */

